[2022-11-26T14:48:45.372+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_preparator_dag.data_train manual__2022-11-26T14:36:13.711317+00:00 [queued]>
[2022-11-26T14:48:45.394+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_preparator_dag.data_train manual__2022-11-26T14:36:13.711317+00:00 [queued]>
[2022-11-26T14:48:45.397+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-26T14:48:45.401+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-11-26T14:48:45.405+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-26T14:48:45.431+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): data_train> on 2022-11-26 14:36:13.711317+00:00
[2022-11-26T14:48:45.461+0000] {standard_task_runner.py:55} INFO - Started process 19461 to run task
[2022-11-26T14:48:45.481+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_preparator_dag', 'data_train', 'manual__2022-11-26T14:36:13.711317+00:00', '--job-id', '486', '--raw', '--subdir', 'DAGS_FOLDER/dag_train_process.py', '--cfg-path', '/tmp/tmpbep27rbv']
[2022-11-26T14:48:45.486+0000] {standard_task_runner.py:83} INFO - Job 486: Subtask data_train
[2022-11-26T14:48:45.603+0000] {task_command.py:376} INFO - Running <TaskInstance: data_preparator_dag.data_train manual__2022-11-26T14:36:13.711317+00:00 [running]> on host 3151441c8efc
[2022-11-26T14:48:45.675+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_preparator_dag
AIRFLOW_CTX_TASK_ID=data_train
AIRFLOW_CTX_EXECUTION_DATE=2022-11-26T14:36:13.711317+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-26T14:36:13.711317+00:00
[2022-11-26T14:48:45.700+0000] {logging_mixin.py:137} INFO - 14
[2022-11-26T14:48:51.100+0000] {warnings.py:110} WARNING - /opt/***/dags/packages/source/net.py:12: RuntimeWarning: overflow encountered in exp
  return np.exp(x) / np.sum(np.exp(x), axis=1, keepdims=True)

[2022-11-26T14:48:51.102+0000] {warnings.py:110} WARNING - /opt/***/dags/packages/source/net.py:12: RuntimeWarning: invalid value encountered in true_divide
  return np.exp(x) / np.sum(np.exp(x), axis=1, keepdims=True)

[2022-11-26T14:48:51.103+0000] {warnings.py:110} WARNING - /opt/***/dags/packages/source/net.py:16: RuntimeWarning: divide by zero encountered in log
  return -np.mean(np.log(y_pred))

[2022-11-26T14:48:54.120+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-11-26T14:48:54.368+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=data_preparator_dag, task_id=data_train, execution_date=20221126T143613, start_date=20221126T144845, end_date=20221126T144854
[2022-11-26T14:48:54.638+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-11-26T14:48:54.737+0000] {taskinstance.py:2623} INFO - 1 downstream tasks scheduled from follow-on schedule check
