[2022-11-29T03:57:18.173+0000] {processor.py:154} INFO - Started process (PID=52) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T03:57:18.177+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T03:57:18.190+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:57:18.190+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T03:57:19.010+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T03:57:19.111+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:57:19.111+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T03:57:19.186+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:57:19.186+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-11-28T00:00:00+00:00, run_after=2022-11-29T00:00:00+00:00
[2022-11-29T03:57:19.257+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 1.108 seconds
[2022-11-29T03:57:56.810+0000] {processor.py:154} INFO - Started process (PID=89) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T03:57:56.812+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T03:57:56.813+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:57:56.813+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T03:57:57.064+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T03:57:57.103+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:57:57.103+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T03:57:57.123+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:57:57.123+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T03:57:57.137+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 0.333 seconds
[2022-11-29T03:58:54.325+0000] {processor.py:154} INFO - Started process (PID=126) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T03:58:54.326+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T03:58:54.329+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:58:54.329+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T03:58:54.616+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T03:58:54.659+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:58:54.658+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T03:58:54.696+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:58:54.696+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T03:58:54.710+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 0.390 seconds
[2022-11-29T04:00:09.527+0000] {processor.py:154} INFO - Started process (PID=165) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:00:09.713+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T04:00:09.784+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:00:09.735+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:00:41.305+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:00:40.070+0000] {timeout.py:68} ERROR - Process timed out, PID: 165
[2022-11-29T04:00:43.106+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:00:41.496+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 73, in <module>
    from pandas.core.frame import DataFrame
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 129, in <module>
    from pandas.core import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 191, in <module>
    class NDFrame(PandasObject, indexing.IndexingMixin):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 8887, in NDFrame
    name_other="mask",
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 348, in doc
    def doc(*docstrings: str | Callable, **params) -> Callable[[F], F]:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 165
[2022-11-29T04:00:44.597+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:00:52.175+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 43.058 seconds
[2022-11-29T04:01:33.197+0000] {processor.py:154} INFO - Started process (PID=203) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:01:33.457+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T04:01:33.695+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:01:33.596+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:02:05.249+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:02:05.195+0000] {timeout.py:68} ERROR - Process timed out, PID: 203
[2022-11-29T04:02:05.640+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:02:05.267+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 11, in <module>
    _nlv = Version(_np_version)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/version/__init__.py", line 336, in __init__
    def __init__(self, version: str) -> None:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 203
[2022-11-29T04:02:05.706+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:02:08.629+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 36.894 seconds
[2022-11-29T04:03:46.859+0000] {processor.py:154} INFO - Started process (PID=235) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:03:47.075+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T04:03:47.581+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:03:47.475+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:04:18.690+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:04:18.497+0000] {timeout.py:68} ERROR - Process timed out, PID: 235
[2022-11-29T04:04:22.987+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:04:19.401+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "pandas/_libs/tslibs/timedeltas.pyx", line 61, in init pandas._libs.tslibs.timedeltas
  File "pandas/_libs/tslibs/fields.pyx", line 49, in init pandas._libs.tslibs.fields
  File "pandas/_libs/tslibs/strptime.pyx", line 1, in init pandas._libs.tslibs.strptime
  File "<frozen importlib._bootstrap>", line 194, in _lock_unlock_module
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 235
[2022-11-29T04:04:26.298+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:04:32.533+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 47.149 seconds
[2022-11-29T04:06:00.128+0000] {processor.py:154} INFO - Started process (PID=243) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:06:01.365+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T04:06:02.448+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:06:02.293+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:07:03.028+0000] {processor.py:154} INFO - Started process (PID=246) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:07:03.067+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T04:07:03.143+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:07:03.143+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:07:33.870+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:07:33.587+0000] {timeout.py:68} ERROR - Process timed out, PID: 246
[2022-11-29T04:07:39.916+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:07:35.162+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "<frozen importlib._bootstrap>", line 194, in _lock_unlock_module
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 246
[2022-11-29T04:07:41.764+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:08:32.578+0000] {processor.py:154} INFO - Started process (PID=249) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:08:32.681+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T04:08:32.736+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:08:32.736+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:09:04.225+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:09:03.003+0000] {timeout.py:68} ERROR - Process timed out, PID: 249
[2022-11-29T04:09:05.053+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:09:04.325+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 11, in <module>
    from pandas.core.arrays.interval import IntervalArray
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/interval.py", line 82, in <module>
    from pandas.core.indexes.base import ensure_index
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 26, in <module>
    import pandas._libs.join as libjoin
  File "pandas/_libs/join.pyx", line 1, in init pandas._libs.join
  File "<frozen importlib._bootstrap>", line 194, in _lock_unlock_module
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 249
[2022-11-29T04:09:05.281+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:09:13.310+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 42.120 seconds
[2022-11-29T04:09:45.750+0000] {processor.py:154} INFO - Started process (PID=254) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:09:46.134+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T04:09:46.452+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:09:46.451+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:10:20.054+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:10:19.822+0000] {timeout.py:68} ERROR - Process timed out, PID: 254
[2022-11-29T04:10:26.297+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:10:24.511+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 254
[2022-11-29T04:10:28.384+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:12:36.151+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 72.763 seconds
[2022-11-29T04:13:28.251+0000] {processor.py:154} INFO - Started process (PID=257) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:13:29.674+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T04:13:31.862+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:13:30.462+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:14:41.474+0000] {processor.py:154} INFO - Started process (PID=260) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:14:42.386+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T04:14:43.140+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:14:43.071+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:15:20.486+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:15:17.255+0000] {timeout.py:68} ERROR - Process timed out, PID: 260
[2022-11-29T04:16:18.778+0000] {processor.py:154} INFO - Started process (PID=263) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:16:19.893+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T04:16:23.534+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:16:20.761+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:19:13.375+0000] {processor.py:154} INFO - Started process (PID=268) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:19:13.412+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T04:19:13.470+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:19:13.460+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:19:44.991+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:19:44.913+0000] {timeout.py:68} ERROR - Process timed out, PID: 268
[2022-11-29T04:19:48.427+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:19:45.371+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/intervaltree.pxi", line 7, in init pandas._libs.interval
  File "pandas/_libs/algos.pyx", line 60, in init pandas._libs.algos
  File "<frozen importlib._bootstrap>", line 1009, in _handle_fromlist
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 268
[2022-11-29T04:19:48.578+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:39:22.212+0000] {processor.py:154} INFO - Started process (PID=50) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:39:22.218+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T04:39:22.226+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:39:22.225+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:39:22.729+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:39:22.909+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:39:22.909+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T04:39:22.938+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:39:22.938+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T04:39:22.978+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 0.781 seconds
[2022-11-29T04:39:56.730+0000] {processor.py:154} INFO - Started process (PID=78) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:39:56.735+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T04:39:56.737+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:39:56.737+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:39:56.980+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:39:57.038+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:39:57.038+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T04:39:57.061+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:39:57.061+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T04:39:57.075+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 0.350 seconds
[2022-11-29T04:41:04.304+0000] {processor.py:154} INFO - Started process (PID=118) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:41:04.508+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T04:41:04.545+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:41:04.545+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:41:34.892+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:41:34.785+0000] {timeout.py:68} ERROR - Process timed out, PID: 118
[2022-11-29T04:41:35.193+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:41:34.975+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 64, in <module>
    from pandas.core.aggregation import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/aggregation.py", line 33, in <module>
    from pandas.core.indexes.api import Index
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/api.py", line 19, in <module>
    from pandas.core.indexes.datetimes import DatetimeIndex
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/datetimes.py", line 62, in <module>
    from pandas.core.indexes.datetimelike import DatetimeTimedeltaMixin
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/datetimelike.py", line 83, in <module>
    class DatetimeIndexOpsMixin(NDArrayBackedExtensionIndex):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/datetimelike.py", line 505, in DatetimeIndexOpsMixin
    def _get_delete_freq(self, loc: int | slice | Sequence[int]):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 118
[2022-11-29T04:41:35.346+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:41:37.445+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 33.416 seconds
[2022-11-29T04:42:09.721+0000] {processor.py:154} INFO - Started process (PID=150) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:42:09.823+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T04:42:10.101+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:42:10.100+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:42:40.668+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:42:40.489+0000] {timeout.py:68} ERROR - Process timed out, PID: 150
[2022-11-29T04:42:41.027+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:42:40.721+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 7, in <module>
    from pandas.core.arrays.categorical import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/categorical.py", line 98, in <module>
    from pandas.core.arrays._mixins import NDArrayBackedExtensionArray
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/_mixins.py", line 69, in <module>
    class NDArrayBackedExtensionArray(NDArrayBacked, ExtensionArray):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/_mixins.py", line 147, in NDArrayBackedExtensionArray
    axis: int = 0,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 391, in decorator
    for component in docstring_components
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 391, in <genexpr>
    for component in docstring_components
  File "/usr/local/lib/python3.7/textwrap.py", line 430, in dedent
    text = _whitespace_only_re.sub('', text)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 150
[2022-11-29T04:42:41.077+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:42:43.188+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 33.854 seconds
[2022-11-29T04:43:18.848+0000] {processor.py:154} INFO - Started process (PID=189) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:43:18.947+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T04:43:18.982+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:43:18.981+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:43:50.001+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:43:49.823+0000] {timeout.py:68} ERROR - Process timed out, PID: 189
[2022-11-29T04:43:50.501+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:43:50.014+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 73, in <module>
    from pandas.core.frame import DataFrame
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 20, in <module>
    from textwrap import dedent
  File "<frozen importlib._bootstrap>", line 1019, in _handle_fromlist
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 189
[2022-11-29T04:43:50.642+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:43:52.242+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 34.961 seconds
[2022-11-29T04:44:29.115+0000] {processor.py:154} INFO - Started process (PID=222) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:44:29.230+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T04:44:29.259+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:44:29.255+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:45:01.929+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:44:59.695+0000] {timeout.py:68} ERROR - Process timed out, PID: 222
[2022-11-29T04:45:02.951+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:45:02.620+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 8, in <module>
    from pandas.core.arrays.datetimes import DatetimeArray
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/datetimes.py", line 67, in <module>
    from pandas.core.arrays import (
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 222
[2022-11-29T04:45:03.089+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:45:04.192+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 35.007 seconds
[2022-11-29T04:45:37.180+0000] {processor.py:154} INFO - Started process (PID=256) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:45:37.272+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T04:45:37.315+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:45:37.315+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:46:36.960+0000] {processor.py:154} INFO - Started process (PID=286) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:46:36.976+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T04:46:36.989+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:46:36.982+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:48:38.954+0000] {processor.py:154} INFO - Started process (PID=320) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:48:38.971+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T04:48:38.986+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:48:38.984+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:49:28.420+0000] {processor.py:154} INFO - Started process (PID=348) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:49:28.448+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T04:49:28.484+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:49:28.483+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:49:59.461+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:49:58.779+0000] {timeout.py:68} ERROR - Process timed out, PID: 348
[2022-11-29T04:49:59.649+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:49:59.487+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 73, in <module>
    from pandas.core.frame import DataFrame
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 129, in <module>
    from pandas.core import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 144, in <module>
    from pandas.core.window import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/window/__init__.py", line 1, in <module>
    from pandas.core.window.ewm import (  # noqa:F401
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/window/ewm.py", line 11, in <module>
    import pandas._libs.window.aggregations as window_aggregations
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 348
[2022-11-29T04:49:59.784+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:50:01.074+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 32.828 seconds
[2022-11-29T04:50:33.140+0000] {processor.py:154} INFO - Started process (PID=385) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:50:33.149+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T04:50:33.156+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:50:33.155+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:51:08.762+0000] {processor.py:154} INFO - Started process (PID=407) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:51:08.784+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T04:51:08.797+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:51:08.796+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:51:17.592+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:51:18.799+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:51:18.796+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T04:51:19.141+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:51:19.141+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T04:51:19.367+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 10.668 seconds
[2022-11-29T04:51:51.702+0000] {processor.py:154} INFO - Started process (PID=429) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:51:51.735+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T04:51:51.750+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:51:51.749+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:52:35.410+0000] {processor.py:154} INFO - Started process (PID=452) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:52:35.423+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T04:52:35.456+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:52:35.456+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:52:46.905+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:52:47.619+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:52:47.612+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T04:52:48.140+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:52:48.104+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T04:52:49.656+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 14.297 seconds
[2022-11-29T04:53:22.471+0000] {processor.py:154} INFO - Started process (PID=475) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:53:22.528+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T04:53:22.541+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:53:22.541+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:54:57.116+0000] {processor.py:154} INFO - Started process (PID=516) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:54:57.153+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T04:54:57.287+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:54:57.285+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T04:55:33.375+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:55:31.861+0000] {timeout.py:68} ERROR - Process timed out, PID: 516
[2022-11-29T04:55:38.074+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:55:35.115+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 516
[2022-11-29T05:07:38.672+0000] {processor.py:154} INFO - Started process (PID=82) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T05:07:38.682+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T05:07:38.694+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:07:38.693+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T05:07:40.472+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T05:07:40.888+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:07:40.888+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T05:07:41.100+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:07:41.100+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T05:07:41.242+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 2.596 seconds
[2022-11-29T05:08:14.388+0000] {processor.py:154} INFO - Started process (PID=117) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T05:08:14.538+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T05:08:14.574+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:08:14.574+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T05:08:46.873+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:08:45.038+0000] {timeout.py:68} ERROR - Process timed out, PID: 117
[2022-11-29T05:08:47.316+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:08:46.955+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 21, in <module>
    from pandas.core.arrays.timedeltas import TimedeltaArray
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/timedeltas.py", line 96, in <module>
    class TimedeltaArray(dtl.TimelikeOps):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/timedeltas.py", line 428, in TimedeltaArray
    self, na_rep="NaT", date_format=None, **kwargs
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/_mixins.py", line 66, in ravel_compat
    return cast(F, method)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 117
[2022-11-29T05:08:47.613+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T05:08:52.612+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 38.577 seconds
[2022-11-29T05:09:26.158+0000] {processor.py:154} INFO - Started process (PID=164) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T05:09:26.197+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T05:09:26.211+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:09:26.209+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T05:09:30.944+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T05:09:33.820+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:09:33.782+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T05:09:34.697+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:09:34.678+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T05:09:34.857+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 8.742 seconds
[2022-11-29T05:10:25.282+0000] {processor.py:154} INFO - Started process (PID=196) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T05:10:25.309+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T05:10:25.330+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:10:25.329+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T05:10:35.606+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T05:10:36.402+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:10:36.400+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T05:10:36.779+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:10:36.778+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T05:10:37.132+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 12.020 seconds
[2022-11-29T05:11:31.296+0000] {processor.py:154} INFO - Started process (PID=236) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T05:11:31.330+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T05:11:31.348+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:11:31.348+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T05:11:42.412+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T05:12:34.763+0000] {processor.py:154} INFO - Started process (PID=258) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T05:12:36.559+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T05:12:37.873+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:12:37.402+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T05:13:11.042+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:13:08.642+0000] {timeout.py:68} ERROR - Process timed out, PID: 258
[2022-11-29T05:13:11.294+0000] {logging_mixin.py:137} WARNING - Exception ignored in: <function _get_module_lock.<locals>.cb at 0xffff6eae6cb0>
[2022-11-29T05:13:12.672+0000] {logging_mixin.py:137} WARNING - Traceback (most recent call last):
[2022-11-29T05:13:13.806+0000] {logging_mixin.py:137} WARNING -   File "<frozen importlib._bootstrap>", line 177, in cb
[2022-11-29T05:13:15.612+0000] {logging_mixin.py:137} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
[2022-11-29T05:13:15.914+0000] {logging_mixin.py:137} WARNING -     raise AirflowTaskTimeout(self.error_message)
[2022-11-29T05:13:15.991+0000] {logging_mixin.py:137} WARNING - airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 258
[2022-11-29T05:15:26.104+0000] {processor.py:154} INFO - Started process (PID=296) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T05:15:26.494+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T05:15:28.962+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:15:27.417+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T05:16:08.876+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:16:04.539+0000] {timeout.py:68} ERROR - Process timed out, PID: 296
[2022-11-29T05:16:53.888+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:16:12.636+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 2, in <module>
    from airflow.operators.python import PythonOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 83, in <module>
    class PythonOperator(BaseOperator):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 183, in PythonOperator
    def determine_kwargs(self, context: Mapping[str, Any]) -> Mapping[str, Any]:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 296
[2022-11-29T05:16:59.475+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T05:17:33.449+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 132.473 seconds
[2022-11-29T05:19:00.302+0000] {processor.py:154} INFO - Started process (PID=350) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T05:19:05.790+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T05:19:09.929+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:19:09.745+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T05:19:58.535+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:19:50.941+0000] {timeout.py:68} ERROR - Process timed out, PID: 350
[2022-11-29T05:20:23.455+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:20:07.362+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 2, in <module>
    from airflow.operators.python import PythonOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 43, in <module>
    from airflow.utils.python_virtualenv import prepare_virtualenv, write_python_script
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/python_virtualenv.py", line 27, in <module>
    from airflow.utils.decorators import remove_task_decorator as _remove_task_decorator
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 350
[2022-11-29T05:20:35.381+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T05:26:16.778+0000] {processor.py:154} INFO - Started process (PID=466) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T05:26:18.315+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T05:26:22.918+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:26:22.144+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T05:26:56.758+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:26:55.880+0000] {timeout.py:68} ERROR - Process timed out, PID: 466
[2022-11-29T07:01:30.249+0000] {processor.py:154} INFO - Started process (PID=50) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:01:30.265+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T07:01:30.273+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:01:30.272+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:01:41.137+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:01:41.698+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:01:41.697+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T07:01:41.873+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:01:41.872+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T07:01:41.973+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 11.748 seconds
[2022-11-29T07:02:17.277+0000] {processor.py:154} INFO - Started process (PID=78) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:02:17.279+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T07:02:17.282+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:02:17.282+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:02:17.513+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:02:17.550+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:02:17.550+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T07:02:17.570+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:02:17.570+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T07:02:17.583+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 0.311 seconds
[2022-11-29T07:03:08.568+0000] {processor.py:154} INFO - Started process (PID=116) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:03:08.570+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T07:03:08.571+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:03:08.571+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:03:08.799+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:03:08.839+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:03:08.839+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T07:03:08.860+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:03:08.860+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T07:03:08.872+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 0.309 seconds
[2022-11-29T07:03:46.632+0000] {processor.py:154} INFO - Started process (PID=152) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:03:46.634+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T07:03:46.636+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:03:46.635+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:03:46.888+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:03:46.948+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:03:46.948+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T07:03:46.969+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:03:46.968+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T07:03:46.982+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 0.354 seconds
[2022-11-29T07:04:27.013+0000] {processor.py:154} INFO - Started process (PID=180) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:04:27.015+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T07:04:27.019+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:04:27.019+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:04:27.236+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:04:27.274+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:04:27.274+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T07:04:27.298+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:04:27.298+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T07:04:27.316+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 0.307 seconds
[2022-11-29T07:05:00.427+0000] {processor.py:154} INFO - Started process (PID=205) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:05:00.431+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T07:05:00.433+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:05:00.433+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:05:10.095+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:05:10.640+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:05:10.636+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T07:05:10.937+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:05:10.933+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T07:05:11.046+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 10.634 seconds
[2022-11-29T07:05:46.373+0000] {processor.py:154} INFO - Started process (PID=228) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:05:46.469+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T07:05:46.499+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:05:46.499+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:06:12.271+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:06:46.484+0000] {processor.py:154} INFO - Started process (PID=261) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:06:46.526+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T07:06:47.364+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:06:47.356+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:06:51.960+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:07:24.782+0000] {processor.py:154} INFO - Started process (PID=283) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:07:24.802+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T07:07:24.808+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:07:24.807+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:07:30.141+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:08:24.019+0000] {processor.py:154} INFO - Started process (PID=324) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:08:24.042+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T07:08:24.046+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:08:24.046+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:09:08.204+0000] {processor.py:154} INFO - Started process (PID=346) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:09:08.212+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T07:09:08.216+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:09:08.216+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:09:58.563+0000] {processor.py:154} INFO - Started process (PID=377) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:09:58.626+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T07:09:58.634+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:09:58.634+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:10:11.047+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:10:31.459+0000] {processor.py:154} INFO - Started process (PID=394) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:10:31.496+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T07:10:31.508+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:10:31.508+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:11:12.369+0000] {processor.py:154} INFO - Started process (PID=417) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:11:12.375+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T07:11:12.379+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:11:12.378+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:12:20.632+0000] {processor.py:154} INFO - Started process (PID=453) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:12:20.835+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T07:12:20.994+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:12:20.959+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:13:04.995+0000] {processor.py:154} INFO - Started process (PID=485) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:13:05.091+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T07:13:05.205+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:13:05.189+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:13:55.359+0000] {processor.py:154} INFO - Started process (PID=511) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:13:55.385+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T07:13:55.388+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:13:55.388+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:13:57.376+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:13:57.890+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:13:57.877+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T07:13:58.160+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:13:58.160+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T07:13:58.392+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 3.305 seconds
[2022-11-29T07:14:29.058+0000] {processor.py:154} INFO - Started process (PID=532) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:14:29.065+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T07:14:29.068+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:14:29.068+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:17:35.870+0000] {processor.py:154} INFO - Started process (PID=564) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:17:35.995+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T07:17:36.184+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:17:36.157+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:18:08.684+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:18:06.833+0000] {timeout.py:68} ERROR - Process timed out, PID: 564
[2022-11-29T07:18:09.689+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:18:08.728+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/__init__.cpython-37m-aarch64-linux-gnu.so'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 11, in <module>
    from pandas.core.arrays.interval import IntervalArray
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/interval.py", line 82, in <module>
    from pandas.core.indexes.base import ensure_index
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1383, in find_spec
  File "<frozen importlib._bootstrap_external>", line 95, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 564
[2022-11-29T07:18:09.997+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:18:12.936+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 37.279 seconds
[2022-11-29T07:18:53.023+0000] {processor.py:154} INFO - Started process (PID=595) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:18:53.273+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T07:18:53.280+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:18:53.279+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:19:25.432+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:19:24.356+0000] {timeout.py:68} ERROR - Process timed out, PID: 595
[2022-11-29T07:19:26.278+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:19:25.495+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 1219, in _path_importer_cache
KeyError: '/home/airflow/.local/lib/python3.7/site-packages/pyarrow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 23, in <module>
    from pandas.compat.pyarrow import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/pyarrow.py", line 6, in <module>
    import pyarrow as pa
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/__init__.py", line 38, in <module>
    from ._generated_version import version as __version__
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1249, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1220, in _path_importer_cache
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 595
[2022-11-29T07:19:26.701+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:19:29.358+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 37.725 seconds
[2022-11-29T07:20:27.919+0000] {processor.py:154} INFO - Started process (PID=642) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:20:28.207+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T07:20:28.368+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:20:28.346+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:21:03.364+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:21:00.362+0000] {timeout.py:68} ERROR - Process timed out, PID: 642
[2022-11-29T07:21:07.252+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:21:03.797+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 642
[2022-11-29T07:21:07.595+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:21:12.165+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 45.821 seconds
[2022-11-29T07:21:51.747+0000] {processor.py:154} INFO - Started process (PID=673) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:21:52.571+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T07:21:53.618+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:21:53.259+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T07:22:34.291+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:22:31.292+0000] {timeout.py:68} ERROR - Process timed out, PID: 673
[2022-11-29T07:22:37.214+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:22:34.575+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 30, in <module>
    from pandas._libs.tslibs import dtypes
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 673
[2022-11-29T07:22:45.870+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T09:37:51.529+0000] {processor.py:154} INFO - Started process (PID=744) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T09:37:52.110+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T09:37:52.464+0000] {logging_mixin.py:137} INFO - [2022-11-29T09:37:52.463+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T09:42:39.256+0000] {processor.py:154} INFO - Started process (PID=127) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T09:42:39.575+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T09:42:39.916+0000] {logging_mixin.py:137} INFO - [2022-11-29T09:42:39.886+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:30:50.882+0000] {processor.py:154} INFO - Started process (PID=157) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:30:50.967+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T16:30:50.990+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:30:50.989+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:31:21.372+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:31:21.199+0000] {timeout.py:68} ERROR - Process timed out, PID: 157
[2022-11-29T16:31:21.884+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:31:21.460+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 143, in <module>
    from pandas.io.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/api.py", line 8, in <module>
    from pandas.io.excel import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/__init__.py", line 6, in <module>
    from pandas.io.excel._odswriter import ODSWriter as _ODSWriter
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_odswriter.py", line 15, in <module>
    from pandas.io.formats.excel import ExcelCell
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 157
[2022-11-29T16:31:21.978+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:31:27.274+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 36.423 seconds
[2022-11-29T16:32:07.130+0000] {processor.py:154} INFO - Started process (PID=186) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:32:07.219+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T16:32:07.298+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:32:07.297+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:32:38.167+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:32:37.693+0000] {timeout.py:68} ERROR - Process timed out, PID: 186
[2022-11-29T16:32:38.744+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:32:38.524+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 143, in <module>
    from pandas.io.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/api.py", line 28, in <module>
    from pandas.io.pytables import (
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 186
[2022-11-29T16:32:38.872+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:32:43.684+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 36.866 seconds
[2022-11-29T16:41:01.214+0000] {processor.py:154} INFO - Started process (PID=80) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:41:01.370+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T16:41:01.389+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:41:01.388+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:41:16.707+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:42:19.574+0000] {processor.py:154} INFO - Started process (PID=124) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:42:19.886+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T16:42:19.936+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:42:19.934+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:42:48.477+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:49:10.107+0000] {processor.py:154} INFO - Started process (PID=50) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:49:10.110+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T16:49:10.112+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:49:10.111+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:49:10.460+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:49:10.563+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:49:10.562+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T16:49:10.611+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:49:10.611+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T16:49:10.636+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 0.534 seconds
[2022-11-29T16:50:35.843+0000] {processor.py:154} INFO - Started process (PID=89) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:50:35.878+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T16:50:35.916+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:50:35.916+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:50:50.596+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:50:53.164+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:50:53.152+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T16:50:54.492+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:50:54.491+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T16:50:55.399+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 19.598 seconds
[2022-11-29T16:51:28.838+0000] {processor.py:154} INFO - Started process (PID=129) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:51:28.855+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T16:51:28.901+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:51:28.899+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:52:09.247+0000] {processor.py:154} INFO - Started process (PID=156) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:52:09.252+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T16:52:09.259+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:52:09.259+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:52:23.636+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:53:15.781+0000] {processor.py:154} INFO - Started process (PID=183) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:53:15.962+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T16:53:16.467+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:53:16.465+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:53:48.049+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:53:47.049+0000] {timeout.py:68} ERROR - Process timed out, PID: 183
[2022-11-29T16:53:48.765+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:53:48.342+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 143, in <module>
    from pandas.io.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/api.py", line 28, in <module>
    from pandas.io.pytables import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/pytables.py", line 3141, in <module>
    class BlockManagerFixed(GenericFixed):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/pytables.py", line 3146, in BlockManagerFixed
    @property
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 183
[2022-11-29T16:53:49.067+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:53:52.823+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 37.304 seconds
[2022-11-29T16:54:32.320+0000] {processor.py:154} INFO - Started process (PID=192) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:54:32.410+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T16:54:32.435+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:54:32.435+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:54:57.845+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:55:07.641+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:55:07.471+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T16:55:10.608+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:55:10.606+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-29T16:55:13.531+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 41.471 seconds
[2022-11-29T16:55:46.348+0000] {processor.py:154} INFO - Started process (PID=196) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:55:46.642+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T16:55:46.800+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:55:46.799+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:56:18.054+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:56:17.332+0000] {timeout.py:68} ERROR - Process timed out, PID: 196
[2022-11-29T16:56:18.790+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:56:18.082+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 73, in <module>
    from pandas.core.frame import DataFrame
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 129, in <module>
    from pandas.core import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 138, in <module>
    from pandas.core.internals.construction import mgr_to_mgr
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 18, in <module>
    import numpy.ma as ma
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 196
[2022-11-29T16:56:19.673+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:56:22.091+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 37.661 seconds
[2022-11-29T16:57:19.335+0000] {processor.py:154} INFO - Started process (PID=218) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:57:19.489+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T16:57:19.629+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:57:19.629+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:57:50.673+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:57:49.886+0000] {timeout.py:68} ERROR - Process timed out, PID: 218
[2022-11-29T16:57:51.002+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:57:50.709+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 64, in <module>
    from pandas.core.aggregation import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/aggregation.py", line 33, in <module>
    from pandas.core.indexes.api import Index
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/api.py", line 28, in <module>
    from pandas.core.indexes.period import PeriodIndex
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/period.py", line 81, in <module>
    ["strftime", "start_time", "end_time"] + PeriodArray._field_ops,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 218
[2022-11-29T16:57:51.623+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:59:58.981+0000] {processor.py:154} INFO - Started process (PID=268) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T16:59:59.581+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T16:59:59.935+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:59:59.930+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T17:00:30.228+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:00:30.080+0000] {timeout.py:68} ERROR - Process timed out, PID: 268
[2022-11-29T17:00:37.836+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:00:32.706+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "pandas/_libs/tslibs/timedeltas.pyx", line 61, in init pandas._libs.tslibs.timedeltas
  File "pandas/_libs/tslibs/fields.pyx", line 49, in init pandas._libs.tslibs.fields
  File "pandas/_libs/tslibs/strptime.pyx", line 633, in init pandas._libs.tslibs.strptime
  File "pandas/_libs/tslibs/strptime.pyx", line 538, in pandas._libs.tslibs.strptime.TimeRE.__init__
  File "pandas/_libs/tslibs/strptime.pyx", line 413, in pandas._libs.tslibs.strptime.LocaleTime.__init__
  File "pandas/_libs/tslibs/strptime.pyx", line 370, in pandas._libs.tslibs.strptime._getlang
  File "/usr/local/lib/python3.7/locale.py", line 591, in getlocale
    return _parse_localename(localename)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 268
[2022-11-29T17:00:39.497+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T17:02:15.746+0000] {processor.py:154} INFO - Started process (PID=297) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T17:02:16.200+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T17:02:16.973+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:02:16.875+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T17:02:52.785+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:02:52.343+0000] {timeout.py:68} ERROR - Process timed out, PID: 297
[2022-11-29T17:02:56.912+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:02:54.718+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "pandas/_libs/tslibs/timestamps.pyx", line 1, in init pandas._libs.tslibs.timestamps
  File "<frozen importlib._bootstrap>", line 194, in _lock_unlock_module
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 297
[2022-11-29T17:02:58.637+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T17:04:25.349+0000] {processor.py:154} INFO - Started process (PID=351) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T17:04:25.961+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T17:04:26.449+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:04:26.300+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T17:04:59.214+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:04:58.332+0000] {timeout.py:68} ERROR - Process timed out, PID: 351
[2022-11-29T17:05:09.691+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:05:03.509+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/timezones.pyx", line 43, in init pandas._libs.tslibs.timezones
  File "/home/airflow/.local/lib/python3.7/site-packages/dateutil/tz/tz.py", line 1557, in __call__
    rv = self.nocache(name=name)
  File "/home/airflow/.local/lib/python3.7/site-packages/dateutil/tz/tz.py", line 1640, in nocache
    tz = tzfile(filepath)
  File "/home/airflow/.local/lib/python3.7/site-packages/dateutil/tz/tz.py", line 478, in __init__
    tzobj = self._read_tzfile(file_stream)
  File "/home/airflow/.local/lib/python3.7/site-packages/dateutil/tz/tz.py", line 619, in _read_tzfile
    tti.delta = datetime.timedelta(seconds=gmtoff)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 351
[2022-11-29T17:05:11.744+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-29T17:06:08.421+0000] {processor.py:154} INFO - Started process (PID=386) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-29T17:06:09.732+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-29T17:06:12.809+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:06:12.273+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
