[2022-11-28T07:36:01.584+0000] {processor.py:154} INFO - Started process (PID=58) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-28T07:36:01.587+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-28T07:36:01.593+0000] {logging_mixin.py:137} INFO - [2022-11-28T07:36:01.593+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-28T07:36:02.248+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-28T07:36:02.359+0000] {logging_mixin.py:137} INFO - [2022-11-28T07:36:02.359+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-28T07:36:02.461+0000] {logging_mixin.py:137} INFO - [2022-11-28T07:36:02.460+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-11-28T00:00:00+00:00, run_after=2022-11-29T00:00:00+00:00
[2022-11-28T07:36:02.515+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 0.945 seconds
[2022-11-28T07:36:43.653+0000] {processor.py:154} INFO - Started process (PID=86) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-28T07:36:43.656+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-28T07:36:43.657+0000] {logging_mixin.py:137} INFO - [2022-11-28T07:36:43.657+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-28T07:36:43.893+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-28T07:36:43.938+0000] {logging_mixin.py:137} INFO - [2022-11-28T07:36:43.938+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-28T07:36:43.970+0000] {logging_mixin.py:137} INFO - [2022-11-28T07:36:43.970+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-11-28T00:00:00+00:00, run_after=2022-11-29T00:00:00+00:00
[2022-11-28T07:36:44.000+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 0.357 seconds
[2022-11-28T07:37:30.744+0000] {processor.py:154} INFO - Started process (PID=123) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-28T07:37:30.747+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-28T07:37:30.750+0000] {logging_mixin.py:137} INFO - [2022-11-28T07:37:30.750+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-28T07:37:31.018+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_generator_dag']) retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-28T07:37:31.063+0000] {logging_mixin.py:137} INFO - [2022-11-28T07:37:31.063+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-28T07:37:31.087+0000] {logging_mixin.py:137} INFO - [2022-11-28T07:37:31.087+0000] {dag.py:3340} INFO - Setting next_dagrun for data_generator_dag to 2022-11-28T00:00:00+00:00, run_after=2022-11-29T00:00:00+00:00
[2022-11-28T07:37:31.101+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 0.364 seconds
[2022-11-28T07:38:40.074+0000] {processor.py:154} INFO - Started process (PID=155) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-28T07:38:40.134+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-28T07:38:40.207+0000] {logging_mixin.py:137} INFO - [2022-11-28T07:38:40.206+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-28T07:39:11.132+0000] {logging_mixin.py:137} INFO - [2022-11-28T07:39:10.774+0000] {timeout.py:68} ERROR - Process timed out, PID: 155
[2022-11-28T07:39:12.384+0000] {logging_mixin.py:137} INFO - [2022-11-28T07:39:11.173+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/intervaltree.pxi", line 7, in init pandas._libs.interval
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 155
[2022-11-28T07:39:12.548+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-28T07:39:16.691+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 37.044 seconds
[2022-11-28T07:42:36.763+0000] {processor.py:154} INFO - Started process (PID=193) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-28T07:42:37.251+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-28T07:42:37.351+0000] {logging_mixin.py:137} INFO - [2022-11-28T07:42:37.317+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-28T07:43:08.694+0000] {logging_mixin.py:137} INFO - [2022-11-28T07:43:08.538+0000] {timeout.py:68} ERROR - Process timed out, PID: 193
[2022-11-28T07:43:09.913+0000] {logging_mixin.py:137} INFO - [2022-11-28T07:43:09.041+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 193
[2022-11-28T07:43:12.821+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-28T08:29:01.379+0000] {processor.py:154} INFO - Started process (PID=243) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-28T08:34:26.839+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-28T08:34:33.062+0000] {logging_mixin.py:137} INFO - [2022-11-28T08:34:28.565+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-28T08:51:41.383+0000] {logging_mixin.py:137} INFO - [2022-11-28T08:51:35.200+0000] {timeout.py:68} ERROR - Process timed out, PID: 243
[2022-11-28T09:38:59.324+0000] {logging_mixin.py:137} INFO - [2022-11-28T08:51:43.232+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 2, in <module>
    from airflow.operators.python import PythonOperator
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 529, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 243
[2022-11-28T09:39:06.254+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
[2022-11-28T13:02:57.081+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_generate_data.py took 257.545 seconds
[2022-11-28T13:06:10.055+0000] {processor.py:154} INFO - Started process (PID=340) to work on /opt/airflow/dags/dag_generate_data.py
[2022-11-28T13:06:11.985+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_generate_data.py for tasks to queue
[2022-11-28T13:06:14.924+0000] {logging_mixin.py:137} INFO - [2022-11-28T13:06:14.073+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_generate_data.py
[2022-11-28T13:21:04.136+0000] {logging_mixin.py:137} INFO - [2022-11-28T13:20:59.619+0000] {timeout.py:68} ERROR - Process timed out, PID: 340
[2022-11-28T14:25:55.370+0000] {logging_mixin.py:137} INFO - [2022-11-28T13:54:31.788+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_generate_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_generate_data.py", line 3, in <module>
    from packages.gen2_data import gen_data
  File "/opt/airflow/dags/packages/gen2_data.py", line 2, in <module>
    import pandas  as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_generate_data.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 340
[2022-11-28T14:26:20.421+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_generate_data.py
