[2022-11-26T14:48:59.087+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_preparator_dag.data_train manual__2022-11-26T14:48:45.962036+00:00 [queued]>
[2022-11-26T14:48:59.096+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_preparator_dag.data_train manual__2022-11-26T14:48:45.962036+00:00 [queued]>
[2022-11-26T14:48:59.096+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-26T14:48:59.097+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-26T14:48:59.098+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-26T14:48:59.106+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): data_train> on 2022-11-26 14:48:45.962036+00:00
[2022-11-26T14:48:59.127+0000] {standard_task_runner.py:55} INFO - Started process 19495 to run task
[2022-11-26T14:48:59.133+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_preparator_dag', 'data_train', 'manual__2022-11-26T14:48:45.962036+00:00', '--job-id', '490', '--raw', '--subdir', 'DAGS_FOLDER/dag_train_process.py', '--cfg-path', '/tmp/tmp07nc_a0e']
[2022-11-26T14:48:59.136+0000] {standard_task_runner.py:83} INFO - Job 490: Subtask data_train
[2022-11-26T14:48:59.225+0000] {task_command.py:376} INFO - Running <TaskInstance: data_preparator_dag.data_train manual__2022-11-26T14:48:45.962036+00:00 [running]> on host 3151441c8efc
[2022-11-26T14:48:59.365+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_preparator_dag
AIRFLOW_CTX_TASK_ID=data_train
AIRFLOW_CTX_EXECUTION_DATE=2022-11-26T14:48:45.962036+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-26T14:48:45.962036+00:00
[2022-11-26T14:48:59.438+0000] {logging_mixin.py:137} INFO - 14
[2022-11-26T14:49:02.421+0000] {warnings.py:110} WARNING - /opt/***/dags/packages/source/net.py:12: RuntimeWarning: overflow encountered in exp
  return np.exp(x) / np.sum(np.exp(x), axis=1, keepdims=True)

[2022-11-26T14:49:02.423+0000] {warnings.py:110} WARNING - /opt/***/dags/packages/source/net.py:12: RuntimeWarning: invalid value encountered in true_divide
  return np.exp(x) / np.sum(np.exp(x), axis=1, keepdims=True)

[2022-11-26T14:49:02.425+0000] {warnings.py:110} WARNING - /opt/***/dags/packages/source/net.py:16: RuntimeWarning: divide by zero encountered in log
  return -np.mean(np.log(y_pred))

[2022-11-26T14:49:03.263+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-11-26T14:49:03.287+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=data_preparator_dag, task_id=data_train, execution_date=20221126T144845, start_date=20221126T144859, end_date=20221126T144903
[2022-11-26T14:49:03.359+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-11-26T14:49:03.393+0000] {taskinstance.py:2623} INFO - 1 downstream tasks scheduled from follow-on schedule check
