[2022-11-26T15:20:08.637+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_preparator_dag.data_train manual__2022-11-26T15:19:55.266771+00:00 [queued]>
[2022-11-26T15:20:08.644+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_preparator_dag.data_train manual__2022-11-26T15:19:55.266771+00:00 [queued]>
[2022-11-26T15:20:08.644+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-26T15:20:08.645+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-26T15:20:08.645+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-26T15:20:08.656+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): data_train> on 2022-11-26 15:19:55.266771+00:00
[2022-11-26T15:20:08.663+0000] {standard_task_runner.py:55} INFO - Started process 147 to run task
[2022-11-26T15:20:08.675+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_preparator_dag', 'data_train', 'manual__2022-11-26T15:19:55.266771+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag_train_process.py', '--cfg-path', '/tmp/tmpf0h55tm5']
[2022-11-26T15:20:08.681+0000] {standard_task_runner.py:83} INFO - Job 7: Subtask data_train
[2022-11-26T15:20:08.785+0000] {task_command.py:376} INFO - Running <TaskInstance: data_preparator_dag.data_train manual__2022-11-26T15:19:55.266771+00:00 [running]> on host 18e45f209dfb
[2022-11-26T15:20:08.869+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_preparator_dag
AIRFLOW_CTX_TASK_ID=data_train
AIRFLOW_CTX_EXECUTION_DATE=2022-11-26T15:19:55.266771+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-26T15:19:55.266771+00:00
[2022-11-26T15:20:08.974+0000] {logging_mixin.py:137} INFO - 15
[2022-11-26T15:20:14.307+0000] {warnings.py:110} WARNING - /opt/***/dags/packages/source/net.py:12: RuntimeWarning: overflow encountered in exp
  return np.exp(x) / np.sum(np.exp(x), axis=1, keepdims=True)

[2022-11-26T15:20:14.314+0000] {warnings.py:110} WARNING - /opt/***/dags/packages/source/net.py:12: RuntimeWarning: invalid value encountered in true_divide
  return np.exp(x) / np.sum(np.exp(x), axis=1, keepdims=True)

[2022-11-26T15:20:14.324+0000] {warnings.py:110} WARNING - /opt/***/dags/packages/source/net.py:16: RuntimeWarning: divide by zero encountered in log
  return -np.mean(np.log(y_pred))

[2022-11-26T15:20:15.377+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-11-26T15:20:15.424+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=data_preparator_dag, task_id=data_train, execution_date=20221126T151955, start_date=20221126T152008, end_date=20221126T152015
[2022-11-26T15:20:15.601+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-11-26T15:20:15.668+0000] {taskinstance.py:2623} INFO - 1 downstream tasks scheduled from follow-on schedule check
